src/Entity/Devis.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass="App\Repository\DevisRepository")
 */
class Devis
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_devis;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(0)
     */
    private $statut = 0;

    /**
     * @ORM\ManyToOne(targetEntity="Client", inversedBy="devis")
     * @ORM\JoinColumn(nullable=true)
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity="Dossier", inversedBy="devis")
     * @ORM\JoinColumn(nullable=true)
     */
    private $dossier;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\OneToMany(targetEntity="DevisArticle", mappedBy="devis", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $devis_article;

    /**
     * @ORM\OneToMany(targetEntity="ArticleExterne", mappedBy="devis", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $article_externe;

    /**
     * @ORM\OneToMany(targetEntity="DevisFraisPort", mappedBy="devis", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $devis_frais_port;

    /**
     * @ORM\OneToMany(targetEntity="DevisFraisCertif", mappedBy="devis", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $devis_frais_certif;

    /**
     * @ORM\OneToMany(targetEntity="DevisMainOeuvre", mappedBy="devis", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $devis_main_oeuvre;

    /**
     * @ORM\OneToMany(targetEntity="Facture", mappedBy="devis")
     * @ORM\JoinColumn(nullable=true)
     */
    private $factures;

    /**
     * @ORM\ManyToMany(targetEntity="DossierArticle", inversedBy="devis")
     */
    private $dossier_articles;

    /**
     * @ORM\ManyToMany(targetEntity="DossierMainOeuvre", inversedBy="devis")
     */
    private $dossier_mainoeuvres;

    /**
     * @ORM\ManyToMany(targetEntity="dossierFraisPort", inversedBy="devis")
     */
    private $dossier_fraisports;

    /**
     * @ORM\ManyToMany(targetEntity="dossierFraisCertif", inversedBy="devis")
     */
    private $dossier_fraiscertifs;

     /**
     * @ORM\Column(type="boolean")
     */
    private $new_devis = 1;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_tva_intra;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $num_tva_intra;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_no_tva;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_exo_tva;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_8_5_tva;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_validite;

    public function __toString()
    {
        return $this->num_devis;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->devis_frais_port = new \Doctrine\Common\Collections\ArrayCollection();
        $this->devis_frais_certif = new \Doctrine\Common\Collections\ArrayCollection();
        $this->devis_main_oeuvre = new \Doctrine\Common\Collections\ArrayCollection();
        $this->devis_article = new \Doctrine\Common\Collections\ArrayCollection();
        $this->article_externe = new \Doctrine\Common\Collections\ArrayCollection();
        $this->frais_port = new \Doctrine\Common\Collections\ArrayCollection();
        $this->frais_certif = new \Doctrine\Common\Collections\ArrayCollection();
        $this->factures = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set numDevis.
     *
     * @param string $numDevis
     *
     * @return Devis
     */
    public function setNumDevis($numDevis)
    {
        $this->num_devis = $numDevis;

        return $this;
    }

    /**
     * Get numDevis.
     *
     * @return string
     */
    public function getNumDevis()
    {
        return $this->num_devis;
    }

    /**
     * Set dateCreation.
     *
     * @param \DateTime $dateCreation
     *
     * @return Devis
     */
    public function setDateCreation($dateCreation)
    {
        $this->date_creation = $dateCreation;

        return $this;
    }

    /**
     * Get dateCreation.
     *
     * @return \DateTime
     */
    public function getDateCreation()
    {
        return $this->date_creation;
    }

    /**
     * Set statut.
     *
     * @param int $statut
     *
     * @return Devis
     */
    public function setStatut($statut)
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * Get statut.
     *
     * @return int
     */
    public function getStatut()
    {
        return $this->statut;
    }

    /**
     * Set client.
     *
     * @param \App\Entity\Client $client
     *
     * @return Devis
     */
    public function setClient(\App\Entity\Client $client = null)
    {
        $this->client = $client;

        return $this;
    }

    /**
     * Get client.
     *
     * @return \App\Entity\Client
     */
    public function getClient()
    {
   		return $this->client;
    }

    /**
     * Set dossier.
     *
     * @param \App\Entity\Dossier|null $dossier
     *
     * @return Devis
     */
    public function setDossier(\App\Entity\Dossier $dossier = null)
    {
        $this->dossier = $dossier;

        return $this;
    }

    /**
     * Get dossier.
     *
     * @return \App\Entity\Dossier|null
     */
    public function getDossier()
    {
        return $this->dossier;
    }

    public function getAppareil()
    {
        if($this->dossier){
            return $this->dossier->getAppareil();
        }else{
            return "";
        }
    }

    public function getDossierTitre()
    {
        if($this->dossier){
            return $this->dossier->getTitre();
        }else{
            return "";
        }
    }


    /**
     * Set commentaire.
     *
     * @param string|null $commentaire
     *
     * @return Devis
     */
    public function setCommentaire($commentaire = null)
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * Get commentaire.
     *
     * @return string|null
     */
    public function getCommentaire()
    {
        return $this->commentaire;
    }

    /**
     * Add devisArticle.
     *
     * @param \App\Entity\DevisArticle $devisArticle
     *
     * @return Devis
     */
    public function addDevisArticle(\App\Entity\DevisArticle $devisArticle)
    {
    	$devisArticle->setDevis($this);
        $this->devis_article[] = $devisArticle;

        return $this;
    }

    /**
     * Remove devisArticle.
     *
     * @param \App\Entity\DevisArticle $devisArticle
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeDevisArticle(\App\Entity\DevisArticle $devisArticle)
    {
        return $this->devis_article->removeElement($devisArticle);
    }

    /**
     * Get devisArticle.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getDevisArticle()
    {
        return $this->devis_article;
    }

    /**
     * Add devisMainOeuvre.
     *
     * @param \App\Entity\DevisMainOeuvre $devisMainOeuvre
     *
     * @return Devis
     */
    public function addDevisMainOeuvre(\App\Entity\DevisMainOeuvre $devisMainOeuvre)
    {
    	$devisMainOeuvre->setDevis($this);
        $this->devis_main_oeuvre[] = $devisMainOeuvre;

        return $this;
    }

    /**
     * Remove devisMainOeuvre.
     *
     * @param \App\Entity\DevisMainOeuvre $devisMainOeuvre
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeDevisMainOeuvre(\App\Entity\DevisMainOeuvre $devisMainOeuvre)
    {
        return $this->devis_main_oeuvre->removeElement($devisMainOeuvre);
    }

    /**
     * Get devisMainOeuvre.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getDevisMainOeuvre()
    {
        return $this->devis_main_oeuvre;
    }


    /**
     * Add devisFraisPort.
     *
     * @param \App\Entity\DevisFraisPort $devisFraisPort
     *
     * @return Devis
     */
    public function addDevisFraisPort(\App\Entity\DevisFraisPort $devisFraisPort)
    {
        $devisFraisPort->setDevis($this);
        $this->devis_frais_port[] = $devisFraisPort;

        return $this;
    }

    /**
     * Remove devisFraisPort.
     *
     * @param \App\Entity\DevisFraisPort $devisFraisPort
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeDevisFraisPort(\App\Entity\DevisFraisPort $devisFraisPort)
    {
        return $this->devis_frais_port->removeElement($devisFraisPort);
    }

    /**
     * Get devisFraisPort.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getDevisFraisPort()
    {
        return $this->devis_frais_port;
    }


    /**
     * Add devisFraisCertif.
     *
     * @param \App\Entity\DevisFraisCertif $devisFraisCertif
     *
     * @return Devis
     */
    public function addDevisFraisCertif(\App\Entity\DevisFraisCertif $devisFraisCertif)
    {
        $devisFraisCertif->setDevis($this);

src/Controller/MecanicienController.php
<?php

namespace App\Controller;

use App\Controller\AdminController as MyAdminController;
use Symfony\Component\Routing\Generator\URLGeneratorInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

class MecanicienController extends MyAdminController
{
    private function generateCarnet($entity){
        $items = array();

        $i = 0;
        foreach(array_reverse($entity->getTravaux()->toArray()) as $travaux)
        {
            if($travaux->getDateSignature()){
                $date = $travaux->getDateSignature()->format("Ymd");
            }else{
                if($travaux->getDossier()->getDateCf()){
                    $date = $travaux->getDossier()->getDateCf()->format("Ymd");
                }else{
                    $date = $travaux->getDossier()->getDateCreation()->format("Ymd");
                }
            }
            $items[$date][$travaux->getDossier()->getId()][$i]['type'] = "travaux";
            $items[$date][$travaux->getDossier()->getId()][$i]['obj'] = $travaux;
            $i++;
        }

        foreach(array_reverse($entity->getTravauxControl()->toArray()) as $travauxCtrl)
        {
            if($travauxCtrl->getDateSignatureControl()){
                $date = $travauxCtrl->getDateSignatureControl()->format("Ymd");
            }else{
                if($travauxCtrl->getDossier()->getDateCf()){
                    $date = $travauxCtrl->getDossier()->getDateCf()->format("Ymd");
                }else{
                    $date = $travauxCtrl->getDossier()->getDateCreation()->format("Ymd");
                }
            }
            $items[$date][$travauxCtrl->getDossier()->getId()][$i]['type'] = "travauxCtrl";
            $items[$date][$travauxCtrl->getDossier()->getId()][$i]['obj'] = $travauxCtrl;
            $i++;
        }

        foreach(array_reverse($entity->getCnad()->toArray()) as $cnad)
        {
            if($cnad->getDateSignature()){
                $date = $cnad->getDateSignature()->format("Ymd");
            }else{
                if($cnad->getDossier()->getDateCf()){
                    $date = $cnad->getDossier()->getDateCf()->format("Ymd");
                }else{
                    $date = $cnad->getDossier()->getDateCreation()->format("Ymd");
                }
            }
            $items[$date][$cnad->getDossier()->getId()][$i]['type'] = "cnad";
            $items[$date][$cnad->getDossier()->getId()][$i]['obj'] = $cnad;
            $i++;
        }

        foreach(array_reverse($entity->getCnadControl()->toArray()) as $cnadCtrl)
        {
            if($cnadCtrl->getDateSignatureControl()){
                $date = $cnadCtrl->getDateSignatureControl()->format("Ymd");
            }else{
                if($cnadCtrl->getDossier()->getDateCf()){
                    $date = $cnadCtrl->getDossier()->getDateCf()->format("Ymd");
                }else{
                    $date = $cnadCtrl->getDossier()->getDateCreation()->format("Ymd");
                }
            }
            $items[$date][$cnadCtrl->getDossier()->getId()][$i]['type'] = "cnadCtrl";
            $items[$date][$cnadCtrl->getDossier()->getId()][$i]['obj'] = $cnadCtrl;
            $i++;
        }

        foreach(array_reverse($entity->getTravauxSup()->toArray()) as $travauxSup)
        {
            
            if($travauxSup->getDateSignature()){
                $date = $travauxSup->getDateSignature()->format("Ymd");
            }else{
                if($travauxSup->getDossier()->getDateCf()){
                    $date = $travauxSup->getDossier()->getDateCf()->format("Ymd");
                }else{
                    $date = $travauxSup->getDossier()->getDateCreation()->format("Ymd");
                }
            }
            $items[$date][$travauxSup->getDossier()->getId()][$i]['type'] = "travauxSup";
            $items[$date][$travauxSup->getDossier()->getId()][$i]['obj'] = $travauxSup;
            $i++;
        }

        foreach(array_reverse($entity->getTravauxSupControl()->toArray()) as $travauxSupCtrl)
        {
            if($travauxSupCtrl->getDateSignatureControl()){
                $date = $travauxSupCtrl->getDateSignatureControl()->format("Ymd");
            }else{
                if($travauxSupCtrl->getDossier()->getDateCf()){
                    $date = $travauxSupCtrl->getDossier()->getDateCf()->format("Ymd");
                }else{
                    $date = $travauxSupCtrl->getDossier()->getDateCreation()->format("Ymd");
                }
            }
            $items[$date][$travauxSupCtrl->getDossier()->getId()][$i]['type'] = "travauxSupCtrl";
            $items[$date][$travauxSupCtrl->getDossier()->getId()][$i]['obj'] = $travauxSupCtrl;
            $i++;
        }

        foreach(array_reverse($entity->getDossier()->toArray()) as $dossier)
        {
            if($dossier->getDateCf()){
                $date = $dossier->getDateCf()->format("Ymd");
            }else{
                $date = $dossier->getDateCreation()->format("Ymd");
            }
            $items[$date][$dossier->getId()][$i]['type'] = "aprs";
            $items[$date][$dossier->getId()][$i]['obj'] = $dossier;
            $items[$date][$dossier->getId()][$i]['qrcode'] = $this->generateUrl('dossier_qrcode', array('entity'=> 'Dossier', 'id'=> $dossier->getId()), URLGeneratorInterface::ABSOLUTE_URL);
            $i++;
        }
        krsort($items);
        //dump($items);

        return $items;
    }

    public function carnetAction()
    {
        $id = $this->request->query->get('id');
        $easyadmin = $this->request->attributes->get('easyadmin');
        $entity = $easyadmin['item'];

        $items = $this->generateCarnet($entity);


        $parameters = array(
            'entity' => $entity,
            'items' => $items,
            'id' =>  $id
        );

        return $this->render("easy_admin/Mecanicien/carnet.html.twig", $parameters);
    }

    
    public function exportAction()
    {
        $id = $this->request->query->get('id');
        $easyadmin = $this->request->attributes->get('easyadmin');
        $entity = $easyadmin['item'];

        $items = $this->generateCarnet($entity);

        $path_pdf = $this->container->get('kernel')->getProjectDir().'/public/carnet_mecanicien/carnet_'.$entity->getTrigramme().'_'.date("Y-m-d").'.pdf';

        if(file_exists($path_pdf)){
            unlink($path_pdf);
        }
        
        $this->container->get('knp_snappy.pdf')->generateFromHtml(
            $this->renderView(
                'easy_admin/Mecanicien/pdf_carnet.html.twig',
                array('entity' => $entity, 'items' => $items)
            ),
            $path_pdf
        );
        $url = $this->request->getScheme().'://'.$this->request->getHttpHost().$this->request->getBasePath().'/public/carnet_mecanicien/carnet_'.$entity->getTrigramme().'_'.date("Y-m-d").'.pdf';
        return new RedirectResponse($url);
    }
}

templates/easy_admin/Mecanicien/carnet.html.twig
{% extends '@EasyAdmin/default/list.html.twig' %}

{% block content_header %}
    <div class="row">
        <div class="col-sm-12">
            {% block content_title_wrapper %}
                <h1 class="title">{% spaceless %}Carnet de mécanicien de {{ entity }} ({{entity.trigramme}}){% endspaceless %}
                	<span class="pull-right">
				        <div class="btn-group">
				            <a href="{{ path('easyadmin', { action: 'export', entity: 'Mecanicien', id: id }) }}" class="btn btn-info" target="blank"><i class="fa fa-download"></i> Export</a>
				        </div>
				    </span>
                </h1>
            {% endblock %}
        </div>
    </div>
{% endblock content_header %}

{% block main %}
	{% include  'easy_admin/Mecanicien/include_carnet.html.twig' with {'entity': entity, 'items': items, pdf: false } %}
{% endblock %}

templates/easy_admin/Mecanicien/include_carnet.html.twig
<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th><span>DATE</span></th>
				<th><span>TYPE</span></th>
				<th><span>IMMAT</span></th>
				<th><span>ATA</span></th>
				<th><span>TACHE</span></th>
				<th><span>LIEU</span></th>
				<th><span>EXECUTION</span></th>
				<th><span>CONTROLE</span></th>
				<th><span>APRS</span></th>
				<th><span>QR CODE</span></th>
			</tr>
		</thead>
		<tbody>
			{% set last_dossier_id = null %}
			{% set new_dossier_line = false %}
			{% for dated_items in items %}
				{% for dossier_id, dossier_id_item in dated_items %}
					{% if dossier_id != last_dossier_id %}
						{% set last_dossier_id = dossier_id %}
						{% set new_dossier_line = true %}
					{% else %}
						{% set new_dossier_line = false %}
					{% endif %}
					{% for items in dossier_id_item %}
						{% if items['type'] == "travaux" or items['type'] == "cnad"  or items['type'] == "travauxSup" %}
							{% if items['obj'].dateSignature is not null %}
								{% set date = items['obj'].dateSignature|date("d/m/Y") %}
							{% else %}
								{% if items['obj'].dossier.dateCf is not null %}
									{% set date = items['obj'].dossier.dateCf|date("d/m/Y") %}
								{% else %}
									{% set date = items['obj'].dossier.dateCreation|date("d/m/Y") %}
								{% endif %}
							{% endif %}
							
						{% elseif items['type'] == "travauxCtrl" or items['type'] == "cnadCtrl" or items['type'] == "travauxSupCtrl" %}
							{% if items['obj'].dateSignatureControl is not null %}
								{% set date = items['obj'].dateSignatureControl|date("d/m/Y") %}
							{% else %}
								{% if items['obj'].dossier.dateCf is not null %}
									{% set date = items['obj'].dossier.dateCf|date("d/m/Y") %}
								{% else %}
									{% set date = items['obj'].dossier.dateCreation|date("d/m/Y") %}
								{% endif %}
							{% endif %}
							
						{% else %}
							{% set date = items['obj'].dateCf|date("d/m/Y") %}
						{% endif %}

						{% if items['type'] == "aprs" %}
							{% set marque = items['obj'].appareil.marqueCellule %}
							{% set model = items['obj'].appareil.modelCellule %}
							{% set immat = items['obj'].appareil.immatriculation %}
							{% set titre_dossier = items['obj'].titre %}
							{% set tache = items['obj'].titre %}
							{% set lieu = items['obj'].lieuCf %}
							{% set qrcode = items['qrcode'] %}
						{% else %}
							{% set marque = items['obj'].dossier.appareil.marqueCellule %}
							{% set model = items['obj'].dossier.appareil.modelCellule %}
							{% set immat = items['obj'].dossier.appareil.immatriculation %}
							{% set titre_dossier = items['obj'].dossier.titre %}
							{% set tache = items['obj'].designation %}
							{% set lieu = "" %}
							{% set qrcode = "" %}
						{% endif %}

						{% if new_dossier_line %}
							<tr class="active">
								<td colspan="10"><b>{{ titre_dossier }}</b></td>
							</tr>
							{% set new_dossier_line = false %}
						{% endif %}

						<tr>
							<td>{{ date }}</td>
							<td>{{ marque }} {{ model }}</td>
							<td>{{ immat }}</td>
							<td></td>
							<td>{{ tache }}</td>
							<td>{{ lieu }}</td>
							<td><i class="fa fa-fw fa{% if items['type'] == "travaux" or items['type'] == "cnad"  or items['type'] == "travauxSup" %}-check{% endif %}-square-o fa-2x"></i></td>
							<td><i class="fa a-fw fa{% if items['type'] == "travauxCtrl" or items['type'] == "cnadCtrl" or items['type'] == "travauxSupCtrl" %}-check{% endif %}-square-o fa-2x"></i></td>
							<td><i class="fa fa-fw fa{% if items['type'] == "aprs" %}-check{% endif %}-square-o fa-2x"></i></td>
							<td>{% if items['type'] == "aprs" %}<img src="{{ qr_code_data_uri(items['qrcode'], { size: 70, margin: 0 }) }}" />{% endif %}</td>
						</tr>
					{% endfor %}
				{% endfor %}
				
			{% endfor %}
		</tbody>
	</table>
</div>

templates/easy_admin/Mecanicien/list.html.twig
{% extends '@EasyAdmin/default/list.html.twig' %}

{% block main %}
	{% set _list_item_actions = easyadmin_get_actions_for_list_item(_entity_config.name) %}

	<div class="row">
	{% for item in paginator.currentPageResults %}
		{% set _item_id = '' ~ attribute(item, _entity_config.primary_key_field_name) %}

		<div class="col-sm-6 {% if loop.index is even %}no_pad_left{% endif %}">
			<div class="box box-widget widget-user-2">
				<div class="widget-user-header bg-green">
					<div class="action-block">
					<table style="background:none; border:none;"><tr data-id="{{ _item_id }}" style="background:none;">
					{% if _list_item_actions|length > 0 %}
                        {% set _column_label =  'list.row_actions'|trans(_trans_parameters, 'EasyAdminBundle') %}
						<td data-label="{{ _column_label }}" class="actions" style="border:none;">
                        {% block item_actions %}
                            {{ include('@EasyAdmin/default/includes/_actions.html.twig', {
                                actions: _list_item_actions,
                                request_parameters: _request_parameters,
                                translation_domain: _entity_config.translation_domain,
                                trans_parameters: _trans_parameters,
                                item_id: _item_id
                            }, with_context = false) }}
                        {% endblock item_actions %}
						</td>
                    {% endif %}
					</tr></table>
                    </div>
					<div class="widget-user-image">
						<img src="{{ vich_uploader_asset(item, 'signatureFile', 'App\\Entity\\Mecanicien') }}" alt="User Avatar">
					</div>
					<h3 class="widget-user-username">{{ item }} ({{item.trigramme}})</h3>
					<h5 class="widget-user-desc">N° Licence <b>{{ item.licence }}</b></h5>
				</div>
			</div>
		</div>
	{% endfor %}
	</div>

	{% block paginator %}
        {{ include(_entity_config.templates.paginator) }}
    {% endblock paginator %}

    {% block delete_form %}
        {% set referer = paginator.currentPage == paginator.nbPages and 1 != paginator.currentPage and 1 == paginator.currentPageResults|length
            ? path('easyadmin', app.request.query|merge({ page: app.request.query.get('page') - 1 }))
            : app.request.requestUri
        %}

        {{ include('@EasyAdmin/default/includes/_delete_form.html.twig', {
            view: 'list',
            referer: referer|url_encode,
            delete_form: delete_form_template,
            _translation_domain: _entity_config.translation_domain,
            _trans_parameters: _trans_parameters,
            _entity_config: _entity_config,
        }, with_context = false) }}
    {% endblock delete_form %}
{% endblock main %}

templates/easy_admin/Mecanicien/pdf_carnet.html.twig
{% extends 'easy_admin/layout_pdf.html.twig' %}

{% block page_title %}Carnet de mécanicien de {{ entity }} ({{entity.trigramme}} du {{ "now"|date("m/d/Y") }}{% endblock %}

{% block body %}

	<div class="row">
        <div class="col-sm-12">
            {% block content_title_wrapper %}
                <h3 class="title">{% spaceless %}Carnet de mécanicien de {{ entity }} ({{entity.trigramme}}) du {{ "now"|date("m/d/Y") }}{% endspaceless %}
                </h3>
            {% endblock %}
        </div>
    </div>

	{% include  'easy_admin/Mecanicien/include_carnet.html.twig' with {'entity': entity, 'items': items, pdf: true } %}
	
{% endblock %}