src/Entity/ArticleMarge.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleMargeRepository")
 */
class ArticleMarge
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $date_change;

    /**
     * @ORM\Column(type="decimal", scale=2)
     * @Assert\GreaterThanOrEqual(0)
     */
    private $marge;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="article_marge")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    public function __toString()
    {
        return $this->marge;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateChange(): ?\DateTimeInterface
    {
        return $this->date_change;
    }

    public function setDateChange(\DateTimeInterface $date_change): self
    {
        $this->date_change = $date_change;

        return $this;
    }

    public function getMarge()
    {
        return $this->marge;
    }

    public function setMarge($marge): self
    {
        $this->marge = $marge;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }
}

templates/easy_admin/flash_messages.html.twig
{% if app.session is not null and app.session.started %}
	<div style="padding-top:10px"></div>
    <div id="flash-messages">
        {% for label, messages in app.session.flashbag.all %}
            {% for message in messages %}
                <div class="alert alert-{{ label }} alert-dismissible">
                	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	                <h4><i class="icon fa fa-check"></i> {{ message|trans }}</h4>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endif %}

templates/easy_admin/label_null.html.twig
<span class="">&nbsp;</span>

templates/easy_admin/last_certificat.html.twig
{{ value }}
<a title="voir le certificat" href="{{ vich_uploader_asset(value, 'certificatFile', 'App\\Entity\\OutillageCertificat') }}" target="_blank"><i class="fa fa-file-pdf-o"></i></a>

templates/easy_admin/layout.html.twig
{% extends '@EasyAdmin/default/layout.html.twig' %}

{% block head_javascript %}
	{% block adminlte_options %}
		<script type="text/javascript">
			var AdminLTEOptions = {
				animationSpeed: 'normal',
				sidebarExpandOnHover: false,
				enableBoxRefresh: true,
				enableBSToppltip: true,
				enableFastclick: true,
				enableControlSidebar: true,
				enableBoxWidget: true
			};
		</script>
	{% endblock %}

	<script src="{{ asset('bundles/easyadmin/javascript/easyadmin-all.min.js') }}"></script>
{% endblock head_javascript %}

{% block header_custom_menu %}
	{% set _logout_path = easyadmin_logout_path() %}
	<ul class="nav navbar-nav">
		{{ render(controller('App\\Controller\\AdminController::notificationsAction')) }}
		<li class="dropdown user user-menu">
			{% block user_menu %}
				<span class="sr-only">{{ 'user.logged_in_as'|trans(domain = 'EasyAdminBundle') }}</span>

				{% if app.user|default(false) == false %}
					<i class="hidden-xs fa fa-user-times"></i>
					{{ 'user.anonymous'|trans(domain = 'EasyAdminBundle') }}
				{% elseif not _logout_path %}
					<i class="hidden-xs fa fa-user"></i>
					{{ app.user.username|default('user.unnamed'|trans(domain = 'EasyAdminBundle')) }}
				{% else %}
					<div class="btn-group">
						<button type="button" class="btn" data-toggle="dropdown">
							<i class="hidden-xs fa fa-user"></i>
							{{ app.user.username|default('user.unnamed'|trans(domain = 'EasyAdminBundle')) }}
						</button>
						<button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu" role="menu">
							{% block user_menu_dropdown %}
							<li>
								<a href="{{ _logout_path }}"><i class="fa fa-sign-out"></i> {{ 'user.signout'|trans(domain = 'EasyAdminBundle') }}</a>
							</li>
							{% if is_granted('ROLE_PREVIOUS_ADMIN') %}
								<li>
									<a href="?_switch_user=_exit"><i class="fa fa-sign-out"></i> {{ 'user.exit_impersonation'|trans(domain = 'EasyAdminBundle') }}</a>
								</li>
							{% endif %}
							{% endblock user_menu_dropdown %}
						</ul>
					</div>
				{% endif %}
			{% endblock user_menu %}
		</li>
	</ul>
{% endblock header_custom_menu %}

{% block flash_messages %}
    {{ include(_entity_config is defined ? _entity_config.templates.flash_messages : '@EasyAdmin/default/flash_messages.html.twig') }}
{% endblock flash_messages %}

{% block body_javascript %}
    <script type="text/javascript">
    	$(function() {
    		$(".field-collection-action").click(function(){
    			$('[data-widget="select2"]').select2({
			        theme: 'bootstrap'
			    });
			})

			$('#dossierarticle_article_formone').prepend('<option selected=""></option>').select2({placeholder: "Sélectionner un article"});
    	});
    </script>
{% endblock body_javascript %}

templates/easy_admin/layout_pdf.html.twig
<html lang="{{ app.request.locale|split('_')|first|default('en') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="robots" content="noindex, nofollow, noarchive, nosnippet, noodp, noimageindex, notranslate, nocache" />
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <meta name="generator" content="EasyAdmin" />

        <title>{% block page_title %}{% endblock %}</title>

        {% block head_stylesheets %}
            <link rel="stylesheet" href="{{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset('bundles/easyadmin/stylesheet/easyadmin-all.min.css') }}">
            <style>
                {{ easyadmin_config('_internal.custom_css')|raw }}
            </style>
        {% endblock %}

        {% for css_asset in easyadmin_config('design.assets.css') %}
            <link rel="stylesheet" href="{{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset(css_asset) }}">
        {% endfor %}

        {% block head_favicon %}
            {% set favicon = easyadmin_config('design.assets.favicon') %}
            <link rel="icon" type="{{ favicon.mime_type }}" href="{{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset(favicon.path) }}" />
        {% endblock %}

        {% block head_javascript %}
            {% block adminlte_options %}
                <script type="text/javascript">
                    var AdminLTEOptions = {
                        animationSpeed: 'normal',
                        sidebarExpandOnHover: false,
                        enableBoxRefresh: false,
                        enableBSToppltip: false,
                        enableFastclick: false,
                        enableControlSidebar: false,
                        enableBoxWidget: false
                    };
                </script>
            {% endblock %}

            <script src="{{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset('bundles/easyadmin/javascript/easyadmin-all.min.js') }}"></script>
        {% endblock head_javascript %}

        {% if easyadmin_config('design.rtl') %}
            <link rel="stylesheet" href="{{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset('bundles/easyadmin/stylesheet/bootstrap-rtl.min.css') }}">
            <link rel="stylesheet" href="{{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset('bundles/easyadmin/stylesheet/adminlte-rtl.min.css') }}">
        {% endif %}
    </head>

    <body id="pdf" class="easyadmin sidebar-mini {% block body_class %}{% endblock %}">
        {% block body %}{% endblock body %}
    </body>
</html>

templates/easy_admin/list_article_marge.html.twig
{# a *-to-many collection of values #}
{% if value is iterable %}
    {% if 'show' == view %}
        {% if value|length > 0 %}
            <ul class="{{ value|length < 2 ? 'inline' }}">
                {% for item in value|slice(0, easyadmin_config('show.max_results')) %}
                    <li>
                        {% if link_parameters is defined %}
                            {# the empty string concatenation is needed when the primary key is an object (e.g. an Uuid object) #}
                            {% set primary_key_value = '' ~ attribute(item, link_parameters.primary_key_name) %}
                            {{ item }} € ( changé le {{ item.dateChange|date("d/m/Y H\\hi") }} )
                            
                        {% else %}
                            {{ item }}
                        {% endif %}
                    </li>
                {% endfor %}

                {% set _remaining_items = value|length - easyadmin_config('show.max_results') %}
                {% if _remaining_items > 0 %}
                    <li class="remaining-items">({{ 'show.remaining_items'|transchoice(_remaining_items, {}, 'EasyAdminBundle') }})</li>
                {% endif %}
            </ul>
        {% else %}
            <div class="empty collection-empty">
                {{ include(entity_config.templates.label_empty) }}
            </div>
        {% endif %}
    {% elseif 'list' == view %}
        <span class="badge">{{ value|length }}</span>
    {% endif %}
{# a simple *-to-one value associated with an entity managed by this backend #}
{% elseif link_parameters is defined %}
    <a href="{{ path('easyadmin', link_parameters|merge({ referer: '' })) }}">{{ value|easyadmin_truncate }}</a>
{% else %}
    {{ value|easyadmin_truncate }}
{% endif %}

templates/easy_admin/list_article_prix.html.twig
{# a *-to-many collection of values #}
{% if value is iterable %}
    {% if 'show' == view %}
        {% if value|length > 0 %}
            <ul class="{{ value|length < 2 ? 'inline' }}">
                {% for item in value|slice(0, easyadmin_config('show.max_results')) %}
                    <li>
                        {% if link_parameters is defined %}
                            {# the empty string concatenation is needed when the primary key is an object (e.g. an Uuid object) #}
                            {% set primary_key_value = '' ~ attribute(item, link_parameters.primary_key_name) %}
                            {{ item }} € ( changé le {{ item.dateChange|date("d/m/Y H\\hi") }} )
                            
                        {% else %}
                            {{ item }}
                        {% endif %}
                    </li>
                {% endfor %}

                {% set _remaining_items = value|length - easyadmin_config('show.max_results') %}
                {% if _remaining_items > 0 %}
                    <li class="remaining-items">({{ 'show.remaining_items'|transchoice(_remaining_items, {}, 'EasyAdminBundle') }})</li>
                {% endif %}
            </ul>
        {% else %}
            <div class="empty collection-empty">
                {{ include(entity_config.templates.label_empty) }}
            </div>
        {% endif %}
    {% elseif 'list' == view %}
        <span class="badge">{{ value|length }}</span>
    {% endif %}
{# a simple *-to-one value associated with an entity managed by this backend #}
{% elseif link_parameters is defined %}
    <a href="{{ path('easyadmin', link_parameters|merge({ referer: '' })) }}">{{ value|easyadmin_truncate }}</a>
{% else %}
    {{ value|easyadmin_truncate }}
{% endif %}

templates/easy_admin/list_certificat.html.twig
{# a *-to-many collection of values #}
{% if value is iterable %}
    {% if 'show' == view %}
        {% if value|length > 0 %}
           <table class="table">
                <tr>
                    <th>Date de validité</th>
                    <th class="text-right">Certificat</th>
                </tr>
                {% for item in value|slice(0, easyadmin_config('show.max_results')) %}
                    <tr>
                        {% if link_parameters is defined %}
                            {# the empty string concatenation is needed when the primary key is an object (e.g. an Uuid object) #}
                            {% set primary_key_value = '' ~ attribute(item, link_parameters.primary_key_name) %}
                            <td>{{ item }}</td>
                            <td class="text-right"><a title="voir le certificat" href="{{ vich_uploader_asset(item, 'certificatFile', 'App\\Entity\\OutillageCertificat') }}" target="_blank"><i class="fa fa-file-pdf-o"></i></a></td>
                        {% else %}
                            <td>{{ item }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}

                {% set _remaining_items = value|length - easyadmin_config('show.max_results') %}
                {% if _remaining_items > 0 %}
                     <tr class="remaining-items"><td>({{ 'show.remaining_items'|transchoice(_remaining_items, {}, 'EasyAdminBundle') }})</td></tr>
                {% endif %}
            </table>
        {% else %}
            <div class="empty collection-empty">
                {{ include(entity_config.templates.label_empty) }}
            </div>
        {% endif %}
    {% elseif 'list' == view %}
        <span class="badge">{{ value|length }}</span>
    {% endif %}
{# a simple *-to-one value associated with an entity managed by this backend #}
{% elseif link_parameters is defined %}
    <a href="{{ path('easyadmin', link_parameters|merge({ referer: '' })) }}">{{ value|easyadmin_truncate }}</a>
{% else %}
    {{ value|easyadmin_truncate }}
{% endif %}

templates/easy_admin/list_formone.html.twig
{# a *-to-many collection of values #}

{% if value is iterable %}
    {% if 'show' == view %}
        {% if value|length > 0 %}
            <table class="table">
                <tr>
                    <th>Sn</th>
                    <th>From Tracking</th>
                    <th class="text-right">Quantité</th>
                    <th class="text-right">Form one</th>
                    <th class="text-right">Frais de port HT par quantité</th>
                    <th class="text-right">Frais de certification HT par quantité</th>
                    <th class="text-right">Action</th>
                </tr>
                {% for item in value|slice(0, easyadmin_config('show.max_results')) %}
                    <tr>
                        {% if link_parameters is defined %}
                            {# the empty string concatenation is needed when the primary key is an object (e.g. an Uuid object) #}
                            {% set primary_key_value = '' ~ attribute(item, link_parameters.primary_key_name) %}
                            <td>{{ item.sn }}</td>
                            <td>{{ item.fromTracking }}</td>
                            <td class="text-right">{{ item.quantite }}</td>
                            <td class="text-right"><a title="voir le Form one" href="{{ vich_uploader_asset(item, 'formoneFile', 'App\\Entity\\ArticleFormone') }}" target="_blank" target="_self"><i class="fa fa-file-pdf-o"></i></a></td>
                            <td class="text-right">{{ item.montantFdpHt }}</td>
                            <td class="text-right">{{ item.montantFdcHt }}</td>
                            <td class="text-right">
                                <a href="{{ path('easyadmin', link_parameters|merge({ id: primary_key_value, menuIndex: '5', action: 'edit', referer: '' })) }}"><i class="fa fa-pencil"></i></a>
                            </td>
                        {% else %}
                            <td>{{ item }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}

                {% set _remaining_items = value|length - easyadmin_config('show.max_results') %}
                {% if _remaining_items > 0 %}
                    <tr class="remaining-items"><td>({{ 'show.remaining_items'|transchoice(_remaining_items, {}, 'EasyAdminBundle') }})</td></tr>
                {% endif %}
            </table>
        {% else %}
            <div class="empty collection-empty">
                {{ include(entity_config.templates.label_empty) }}
            </div>
        {% endif %}
    {% elseif 'list' == view %}
        <span class="badge">{{ value|length }}</span>
    {% endif %}
{# a simple *-to-one value associated with an entity managed by this backend #}
{% elseif link_parameters is defined %}
    <a href="{{ path('easyadmin', link_parameters|merge({ referer: '' })) }}">{{ value|easyadmin_truncate }}</a>
{% else %}
    {{ value|easyadmin_truncate }}
{% endif %}

templates/easy_admin/list_pe.html.twig
{# a *-to-many collection of values #}
{% if value is iterable %}
    {% if 'show' == view %}
        {% if value|length > 0 %}
            <table class="table">
                <tr>
                    <th>Type</th>
                    <th>Edition</th>
                    <th>Révision / Acceptation</th>
                    <th>Date</th>
                    <th class="text-right">Action</th>
                </tr>
                {% for item in value|slice(0, easyadmin_config('show.max_results')) %}
                    <tr>
                        {% if link_parameters is defined %}
                            {# the empty string concatenation is needed when the primary key is an object (e.g. an Uuid object) #}
                            {% set primary_key_value = '' ~ attribute(item, link_parameters.primary_key_name) %}
                            <td>{{ item.type }}</td>
                            <td>{{ item.edition }}</td>
                            <td>{{ item.revision }}</td>
                            <td>{{ item.date|date("d/m/Y") }}</td>
                            <td class="text-right">
                                <a href="{{ path('easyadmin', link_parameters|merge({ id: primary_key_value, action: 'edit', referer: '' })) }}"><i class="fa fa-pencil"></i></a>
                            </td>                   
                        {% else %}
                            <td>{{ item }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}

                {% set _remaining_items = value|length - easyadmin_config('show.max_results') %}
                {% if _remaining_items > 0 %}
                    <tr class="remaining-items"><td>({{ 'show.remaining_items'|transchoice(_remaining_items, {}, 'EasyAdminBundle') }})</td></tr>
                {% endif %}
            </table>
        {% else %}
            <div class="empty collection-empty">
                {{ include(entity_config.templates.label_empty) }}
            </div>
        {% endif %}
    {% elseif 'list' == view %}
        <span class="badge">{{ value|length }}</span>
    {% endif %}
{# a simple *-to-one value associated with an entity managed by this backend #}
{% elseif link_parameters is defined %}
    <a href="{{ path('easyadmin', link_parameters|merge({ referer: '' })) }}">{{ value|easyadmin_truncate }}</a>
{% else %}
    {{ value|easyadmin_truncate }}
{% endif %}

templates/easy_admin/notifications.html.twig
<li class="dropdown notifications-menu" style="float:right;">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<i class="fa fa-bell-o text-white"></i>
		{% if alertes|length > 0 %}<span class="label label-danger">{{ alertes|length }}</span>{% endif %}
	</a>
	<ul class="dropdown-menu">
		{% if alertes|length > 0 %}
		<li class="header">Vous avez {{ alertes|length }} notifications</li>
		<li>
			<ul class="menu">
				{% for alerte in alertes %}
				<li>
					{% if alerte.type == 0 %}
					<a href="{{ path('easyadmin', { action: 'show', entity: alerte.nameEntity, primary_key_name: 'id', id: alerte.idEntity, referer: '' }) }}">
						<i class="fa fa-tags text-green"></i> {{ alerte.designation }}
					</a>
					{% elseif alerte.type == 1 %}
					<a href="{{ path('easyadmin', { action: 'list', entity: alerte.nameEntity, primary_key_name: 'id', id: alerte.idEntity, referer: '' }) }}">
						<i class="fa fa-gears text-blue"></i> {{ alerte.designation }}
					</a>
					{% endif %}
				</li>
				{% endfor %}
			</ul>
		</li>
		{% else %}
		<li class="header">Vous n'avez pas de notifications</li>
		{% endif %}
	</ul>
</li>

templates/easy_admin/outillage_type.html.twig
{% if field_options.format %}
    {% set type_id = field_options.format|format(value) %}
{% else %}
    {% set type_id = value|number_format %}
{% endif %}

{% for name, id in field_options.type_outillage %}
	{% if id == type_id %}
		{{ name }}
	{% endif %}
{% endfor %}

templates/easy_admin/show.html.twig
{% extends '@EasyAdmin/default/show.html.twig' %}


{% block main %}
    <div class="form-horizontal">
        {% block pre_show_field %}{% endblock %}
        {% block show_fields %}
            {% for field, metadata in fields %}
                {% block show_field %}
                    <div class="form-group field-{{ metadata.type|default('default')|lower }} {{ metadata.css_class|default('') }}">
                        <label class="col-sm-2 control-label">
                            {{ (metadata.label ?: field|humanize)|trans(_trans_parameters)|raw }}
                        </label>
                        <div class="col-sm-10">
                            <div class="form-control">
                                {{ easyadmin_render_field_for_show_view(_entity_config.name, entity, metadata) }}
                            </div>

                            {% if metadata.help|default('') != '' %}
                                <span class="help-block"><i class="fa fa-info-circle"></i> {{ metadata.help|trans|raw }}</span>
                            {% endif %}
                        </div>
                    </div>
                {% endblock %}
            {% endfor %}
        {% endblock %}
        {% block post_show_field %}{% endblock %}

        <div class="form-group form-actions">
            <div class="col-sm-10 col-sm-offset-2">
            {% block item_actions %}
                {% set _show_actions = easyadmin_get_actions_for_show_item(_entity_config.name) %}
                {% set _request_parameters = { entity: _entity_config.name, referer: app.request.query.get('referer') } %}

                {{ include('@EasyAdmin/default/includes/_actions.html.twig', {
                    actions: _show_actions,
                    request_parameters: _request_parameters,
                    translation_domain: _entity_config.translation_domain,
                    trans_parameters: _trans_parameters,
                    item_id: _entity_id
                }, with_context = false) }}
            {% endblock item_actions %}
            </div>
        </div>
    </div>

    {% block delete_form %}
        {{ include('@EasyAdmin/default/includes/_delete_form.html.twig', {
            view: 'show',
            referer: app.request.query.get('referer', ''),
            delete_form: delete_form,
            _translation_domain: _entity_config.translation_domain,
            _trans_parameters: _trans_parameters,
            _entity_config: _entity_config,
        }, with_context = false) }}
    {% endblock delete_form %}
{% endblock %}

templates/easy_admin/statut_list.html.twig
{% if field_options.format %}
    {% set type_id = field_options.format|format(value) %}
{% else %}
    {% set type_id = value|number_format %}
{% endif %}

<span class="label {% if type_id == 1 %}label-success{% else %}label-warning{% endif %}">{{ field_options.statut[type_id] }}</span>